name: opensplice
channels:
  - conda-forge
  - bioconda
  - defaults
  - khchao
dependencies:
  - python=3.10
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - biopython
  - h5py
  - pysam
  - gffutils
  - pip
  - pip:
      - openspliceai==0.0.4
      - pyfaidx==0.9.0.3
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
